export const TOPICS = {
  ORDER_EVENTS: 'order.events',
  USER_EVENTS: 'users.events',
  INVENTORY_EVENTS: 'inventory.events',
  DLQ: 'dlq',
  OTHER_EVENTS: 'other.events',
} as const

export const USER_EVENTS_TYPE = {
  USER_CREATED: 'USER_CREATED',
} as const

export const DLQ_EVENTS_TYPE = {
  DLQ_MESSAGE: 'DLQ_MESSAGE',
} as const

export const INVENTORY_EVENTS_TYPE = {
  PRODUCT_ADDED: 'INVENTORY_PRODUCT_ADDED',
  BULK_ADDED: 'INVENTORY_BULK_ADDED',
  PROUCT_UPDATED: 'INVENTORY_PRODUCT_UPDATED',
  STOCK_RESERVED: 'INVENTORY_STOCK_RESERVED',
  RESERVATION_CONFIRMED: 'INVENTORY_RESERVATION_CONFIRMED',
  RESERVATION_CANCELLED: 'INVENTORY_RESERVATION_CANCELLED',
} as const
