// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import * as path from 'path'
import * as dotenv from 'dotenv'
import { defineConfig, env } from 'prisma/config'

dotenv.config({
  quiet: true,
  path: path.resolve(__dirname, '../../.env.local'),
})

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: env('ORDER_DB_URL'),
  },
})
